export enum constants {
    EVIMGR_COUNTER_PLUS_ONE = "EVIMGR_COUNTER_PLUS_ONE",
    EVIMGR_COUNTER_MINUS_ONE = "EVIMGR_COUNTER_MINUS_ONE",
    EVIMGR_COUNTER_PLUS_NUMBER = "EVIMGR_COUNTER_PLUS_NUMBER",

    
    EVIMGR_LOGIN = "EVIMGR_LOGIN",
    EVIMGR_LOGIN_F = "EVIMGR_LOGIN_F",
    EVIMGR_LOGIN_B = "EVIMGR_LOGIN_B",

    FFF = 0,
    XXX,
}